/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.AltenticarUsuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author VAIO
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
       
    private final AltenticarUsuario controller;
    public LoginView() {
        initComponents();
        controller = new AltenticarUsuario(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_Label = new javax.swing.JLabel();
        LoginUsuario = new javax.swing.JTextField();
        Senha_Label = new javax.swing.JLabel();
        SenhaUsuario = new javax.swing.JPasswordField();
        Entrar_Button = new javax.swing.JButton();
        Cadastrar_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login_Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Login_Label.setForeground(new java.awt.Color(255, 255, 255));
        Login_Label.setText("Login:");
        getContentPane().add(Login_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 110, -1));

        LoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(LoginUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 260, 30));

        Senha_Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Senha_Label.setForeground(new java.awt.Color(255, 255, 255));
        Senha_Label.setText("Senha:");
        getContentPane().add(Senha_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 80, -1));

        SenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(SenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 260, 30));

        Entrar_Button.setBackground(new java.awt.Color(102, 255, 102));
        Entrar_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entrar_Button.setText("Entrar");
        Entrar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, 30));

        Cadastrar_Button.setBackground(new java.awt.Color(0, 102, 255));
        Cadastrar_Button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cadastrar_Button.setText("Cadastrar");
        Cadastrar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 115, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundoLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsuarioActionPerformed

    private void SenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaUsuarioActionPerformed

    private void Entrar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar_ButtonActionPerformed
        try {
               this.controller.autenticar();
            } catch (SQLException ex) {
                Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_Entrar_ButtonActionPerformed

    private void Cadastrar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_ButtonActionPerformed
        CadastroView telaDeCadastro = new CadastroView();
        telaDeCadastro.setVisible(true);
    }//GEN-LAST:event_Cadastrar_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar_Button;
    private javax.swing.JButton Entrar_Button;
    private javax.swing.JTextField LoginUsuario;
    private javax.swing.JLabel Login_Label;
    private javax.swing.JPasswordField SenhaUsuario;
    private javax.swing.JLabel Senha_Label;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JTextField getLoginUsuario() {
        return LoginUsuario;
    }

    public void setLoginText(JTextField LoginText) {
        this.LoginUsuario = LoginText;
    }

    public JPasswordField getSenhaUsuario() {
        return SenhaUsuario;
    }

    public void setSenha_Text(JPasswordField Senha_Text) {
        this.SenhaUsuario = Senha_Text;
    }

    public void exibirMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null,mensagem);
    }


}
